# Generated by Django 3.0.6 on 2024-05-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprediction',
            name='language',
            field=models.CharField(default='English', max_length=255),
            preserve_default=False,
        ),
    ]
